/**
 * config.js
 * 定义与业务相关的常量
 */
// task状态
const TASK_STATE_NON_RELEASED = 'non-released'
const TASK_STATE_RELEASED = 'released'
const TASK_STATE_CLOSED = "closed"

// task类型
const TASK_KIND_QUESTIONNAIRE = 'questionnaire'

// deal状态
const DEAL_STATE_UNDERWAY = "underway"
const DEAL_STATE_CLOSURE = "CLOSURE"

export default {
  TASK_STATE_NON_RELEASED: TASK_STATE_NON_RELEASED,
  TASK_STATE_RELEASED: TASK_STATE_RELEASED,
  TASK_STATE_CLOSED: TASK_STATE_CLOSED,
  TASK_KIND_QUESTIONNAIRE: TASK_KIND_QUESTIONNAIRE,
  DEAL_STATE_UNDERWAY: DEAL_STATE_UNDERWAY,
  DEAL_STATE_CLOSURE: DEAL_STATE_CLOSURE
}